name: Run Python Script Hourly

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'  # Runs at the start of every hour

permissions:
  actions: write
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Python Script
      run: |
        python .github/workflows/python.py
    - name: Commit and Push Changes
      run: |
        git commit -m "Update banner"
        git push -u origin main