name: Banner Refresher

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'  # Runs at the start of every hour

permissions:
  actions: write
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Python Script
      run: |
        python .github/workflows/python.py
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/current_chances.json
        git commit -a -m "Updated Banner"
        git push -u origin main

      
       